// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJylHwfkzsntuvFgN29i2tspplyQ7nU8s',
    appId: '1:685652855514:web:f4e706a04a728b6c5f73e3',
    messagingSenderId: '685652855514',
    projectId: 'engage-app-ce1dc',
    authDomain: 'engage-app-ce1dc.firebaseapp.com',
    storageBucket: 'engage-app-ce1dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDarlqHqpLgTye2mkOOMef-cVTz3-w2p9k',
    appId: '1:685652855514:android:11f92ec5621b8f505f73e3',
    messagingSenderId: '685652855514',
    projectId: 'engage-app-ce1dc',
    storageBucket: 'engage-app-ce1dc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMAJvkxeE3tBbkXYczRKBxJ7Z4qMkkXGc',
    appId: '1:685652855514:ios:9625d09312ec4e575f73e3',
    messagingSenderId: '685652855514',
    projectId: 'engage-app-ce1dc',
    storageBucket: 'engage-app-ce1dc.firebasestorage.app',
    iosBundleId: 'com.example.engage',
  );
}
